Support DLedger for Snapshots (temp version)
openmessaging/dledger pull request #197
Opened 2022-08-10 12:05 UTC by tsunghanjacktsai

2022-08-29 01:16 UTC, RongtongJin requested changes

2022-08-29 01:16 UTC, RongtongJin commented on src/main/java/io/openmessaging/storage/dledger/snapshot/file/FileSnapshotStorage.java
> +            }
可以再上一个循环就把最后一个lastSnapshotIndex找出来，不需要放在Collections里排序

2022-08-29 01:16 UTC, RongtongJin commented on src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java
> +        }
shutdown 也要判断是否是 null

2022-08-29 01:16 UTC, RongtongJin commented on src/main/java/io/openmessaging/storage/dledger/store/file/DLedgerMmapFileStore.java
> +        }
应该是判断是否是null而不是isStatemachineEnable

2022-09-01 03:28 UTC, RongtongJin commented on src/main/java/io/openmessaging/storage/dledger/DLedgerServer.java
> +        }
需要在代码中保证必须是先注册，再启动，否则抛出错误

2022-09-01 03:28 UTC, RongtongJin commented on src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachineCaller.java
> +        SnapshotMeta snapshotMeta = new SnapshotMeta(this.lastAppliedIndex.get(), this.lastAppliedTerm);
如何保证this.lastAppliedIndex.get(), this.lastAppliedTerm和SaveSnapshotHook saveSnapshotAfter中的dledger entry的index和term一致？因为中间可能有其他apply Task进入

2022-09-01 07:52 UTC, RongtongJin commented
Hi, @hzh0425  @mxsm  @TheR1sing3un Plz help review this PR if you have time.

2022-09-10 15:40 UTC, TheR1sing3un commented
Hi~Please resolve the conflicts if you have time~

2022-09-17 16:56 UTC, tsunghanjacktsai commented on dledger/src/main/java/io/openmessaging/storage/dledger/statemachine/StateMachineCaller.java
> +        if (this.error != null || this.snapshotManager.isLoadingSnapshot()) {
@RongtongJin Done.

2022-09-21 07:37 UTC, mxsm commented on dledger/src/main/java/io/openmessaging/storage/dledger/snapshot/SnapshotManager.java
> +    }
Concurrency issue

2022-10-10 09:47 UTC, RongtongJin approved these changes

2022-10-10 09:47 UTC, merged