code styles fix
openmessaging/dledger pull request #233
Opened 2022-09-14 15:06 UTC by akkw

处理了代码里面明显的警告

2022-09-15 02:02 UTC, tsunghanjacktsai requested changes
@akkw May need to check how CI failed.

2022-09-15 08:10 UTC, RongtongJin commented on dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
> +            assert truncateEntry != null;
Why should we check again here?

2022-09-15 08:10 UTC, RongtongJin commented on dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
>          private boolean checkAndFreshState() {
This is mainly to check whether it is the master, so I think the original logic is more smooth

2022-09-19 15:09 UTC, akkw commented on dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
> +            assert truncateEntry != null;
这里可能是我处理太快，没有看到上面的校验

2022-09-19 15:20 UTC, akkw commented on dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
>          private boolean checkAndFreshState() {
总觉得非操作会使逻辑计算变得复杂，这里换一个方法名可以吗？把不为master体现出来

2022-09-19 15:22 UTC, akkw commented on dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
> +            assert truncateEntry != null;
> Why should we check again here?

我继续检查一下其他代码

2022-09-20 02:17 UTC, RongtongJin commented on dledger/src/main/java/io/openmessaging/storage/dledger/DLedgerEntryPusher.java
>          private boolean checkAndFreshState() {
> 总觉得非操作会使逻辑计算变得复杂，这里换一个方法名可以吗？把不为master体现出来

可以的哈

2022-10-06 11:32 UTC, merged